### ISSUE TITLE
X Prefix in ExtraTables

### ISSUE THREAD

**Issue by solverat** [selectline-software/selectline-api#271]
We're currently struggling with a nasty breaking change which has been releases within 22.2:

![image](https://user-images.githubusercontent.com/700119/195329574-1a50980f-3e89-4a85-ba02-76687a0a97e5.png)

We could not find an active changelog either, but only this one:
https://www.selectline.ch/newsletter/Aenderungen_und_Neuerungen_SelectLine.htm#22.2

***

Our implementation is **heavily** dependent on these`ExtraTable`, and we're also using them for writing operations. 

There was never an indication that you're going to disallow writing on`ExtraTables` with an X-Prefix only, which will bring us to a major issue: All ExtraTables within our client implementation does not come with any X-Prefixes.
 
Also, you released this breaking change within a minor release without any deprecation note.

- Is there any solution to disable this rule by changing a configuration flag?
- There must be a good reason why you've restricted those `ExtraTables`, some insights would be great!

Maybe related: https://github.com/selectline-software/selectline-api/issues/232

**Comment by benwalch** [comment]
@MatthiasGuse a quick information regarding this issue would be much appreciated!
This issue broke most of our application. We are using the `ExtraTable` endpoint for managing data in tables `CRM_SOCIALMEDIA`, `CRM_BEZIEHUNGEN`, `CRM_ADRESSEN_EXTRA`, `CRM_STICHWORTLINK` and so on - which are - according to our selectline broker - standard tables in selectline) and for writing data to custom fields (fields beginning with an underscore).

**Comment by MatthiasGuse** [comment]
Hello,

we documented this change in the changetext you mentioned and our documentation of technical changes for the Version 22.2:
![grafik](https://user-images.githubusercontent.com/31447000/195841830-3164fbb8-b2e5-4c9c-bb46-59862c8f3a82.png)

We changed this, because it was possible to get invalid records in SelecLine tables that were not intended. An error from our point of view. See #244 and #247.

To do such things on your own risk, you can use the macro functions. See API documentation or her #144 

Best regards

Matthias
